apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8001
      targetPort: 8001
    - name: debug
      port: 5001
      targetPort: 5001
  selector:
    app: warehouse-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
  labels:
    app: warehouse-service
spec:
  selector:
    matchLabels:
      app: warehouse-service
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: warehouse-service
    spec:
      containers:
        - name: warehouse-service
          image: warehouse-service-image
          env:
          - name: OTEL_SERVICE_NAME
            value: warehouse-service
          - name: OTEL_METRICS_EXPORTER
            value: none
          - name: JAVA_TOOL_OPTIONS
            value: -agentlib:jdwp=transport=dt_socket,address=5001,server=y,suspend=n
          ports:
            - containerPort: 8001
            - containerPort: 5001
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
