apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8000
      targetPort: 8000
    - name: debug
      port: 5000
      targetPort: 5000
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service-image
          env:
            - name: OTEL_SERVICE_NAME
              value: order-service
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,address=5000,server=y,suspend=n
          ports:
            - containerPort: 8000
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
