local_resource('order-service-compile', './gradlew compileJava', deps=['src', 'build.gradle'], labels='App')
custom_build('order-service-image', './gradlew jibDockerBuild --image $EXPECTED_REF',
  live_update = [
    sync('./build/classes/java/main', '/app/classes'),
  ],
  deps=['./build/classes', 'build.gradle'],
  entrypoint='find /app | java -cp /app/resources:/app/classes:/app/libs/* inner.loop.demo.OrderServiceApplication'
)
k8s_yaml('deployment.yaml')

def order_service(dependencies):
  dependencies.extend(['order-service-compile'])
  k8s_resource('order-service', port_forwards=[8000,5000], resource_deps=dependencies, labels='App')