apiVersion: v1
kind: Service
metadata:
  name: demo-base-java
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: demo-base-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-base-java
  labels:
    app: demo-base-java
spec:
  selector:
    matchLabels:
      app: demo-base-java
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      labels:
        app: demo-base-java
    spec:
      containers:
        - name: demo-base-java
          image: demo-base-java-image
          ports:
            - containerPort: 8000
